import { Selector } from 'testcafe';
export default {
	baseURL: 'https://www.saucedemo.com/',
	userNameInput: Selector('#user-name'),
	pwdInput: Selector('#password'),
	standardUser: 'standard_user',
	performanceGlichUser: 'performance_glitch_user',
	lockedOutUser: 'locked_out_user',
	problemUser: 'problem_user',
	pwd: 'secret_sauce',
	loginButton: Selector('#login-button'),
	loginLogo: Selector('.login_logo'),
	loginBox: Selector('.login-box'),
	inventoryList: Selector('.inventory_list').filterVisible(),
	menuButton: Selector('.bm-burger-button').find('button'),
	navMenu: Selector('.bm-menu-wrap'),
	logoutButton: Selector('.bm-menu-wrap').find('#logout_sidebar_link'),
	lockedOutError: Selector('h3').withAttribute('data-test', 'error').withText('Epic sadface: Sorry, this user has been locked out.'),
	usernameRequiredError: Selector('h3').withAttribute('data-test', 'error').withText('Epic sadface: Username is required'),
	firstnameRequiredError: Selector('h3').withAttribute('data-test', 'error').withText('Error: First Name is required'),
	lastnameequiredError: Selector('h3').withAttribute('data-test', 'error').withText('Error: Last Name is required'),
	zipRequiredError: Selector('h3').withAttribute('data-test', 'error').withText('Error: Postal Code is required'),
	noMatchError: Selector('h3').withAttribute('data-test', 'error').withText('Epic sadface: Username and password do not match any user in this service'),
	productSortSelect: Selector('.product_sort_container'),
	inventoryItem: Selector('.inventory_item'),
	inventoryItemPrice: Selector('.inventory_item_price').filterVisible(),
	inventoryItemName: Selector('.inventory_item_name'),
	cartItem: Selector('.cart_list').find('.cart_item'),
	addToCartButton: Selector('button').withAttribute('id', /add-/),
	removeFromCartButton: Selector('button').withAttribute('id', /remove-/),
	removeButton: Selector('.pricebar').find('button').withText('Remove'),
	shoppingCartIcon: Selector('#shopping_cart_container'),
	shoppingCartBadge: Selector('.shopping_cart_badge'),
	cartList: Selector('.cart_list'),
	continueShoppingButton: Selector('#continue-shopping'),
	checkoutButton: Selector('#checkout'),
	checkoutInfoForm: Selector('.checkout_info'),
	firstNameInput: Selector('#first-name'),
	lastNameInput: Selector('#last-name'),
	zipCodeInput: Selector('#postal-code'),
	continueButton: Selector('#continue'),
	summaryInfo: Selector('.summary_info'),
	subtotalLabel: Selector('.summary_subtotal_label'),
	finishButton: Selector('#finish'),
	checkoutCompleteContainer: Selector('#checkout_complete_container'),
	backHomeButton: Selector('#back-to-products'),
	inventoryDetailsContainer: Selector('.inventory_details_container'),
	inventoryDetailsImage: Selector('.inventory_details_img'),
	inventoryDetailsName: Selector('.inventory_details_name'),
	inventoryDetailsDesc: Selector('.inventory_details_desc'),
	inventoryDetailsPrice: Selector('.inventory_details_price'),
	backToProductsButton: Selector('.inventory_details_back_button'),
	cancelButton: Selector('#cancel'),
	stepTwoItem: Selector('.cart_item'),
	taxLabel: Selector('.summary_tax_label'),
	totalLabel: Selector('.summary_total_label')

}